### ISSUE TITLE
Update Drupal core

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#1]
**Site**
https://d1-connect-d8-develop.enroll.tufts.edu/
**Tasks**

- [ ] Update Drupal 8.8.5 to most recent version

- [ ] Test

- [ ] Client review & fixes (if needed) - will happen first or second week of August

- [ ] Deploy to prod

**Comment by ericmaster** [comment]
Currently updated to the most stable Drupal 8 version which is 8.9.3. Also available Drupal 9.0.3 but that will need to make sure that no deprecated calls are being used by custom and contrib modules so currently not recommended until most contrib modules have release a D9 compliant release.

No specific testing steps except verify the overall correct functionality of the site.

**Comment by ericmaster** [comment]
Currently deployed to dev until issue in stage env deployment is resolved.

**Comment by ericmaster** [comment]
Deployed to stage, verify version at https://d1-connect-d8-stage.enroll.tufts.edu/admin/reports/status
