### ISSUE TITLE
INDDEX site - field addition

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#11]
See attached images​​​​:  I'd (Annie) added a citation field to the Case Study content type. It just needs to be a plain text field, no links, but it also needs to accept copied and pasted characters as described in the bullet point above. For the launch of their site, I had them add the citation language to the top of the main text field as a workaround, but they'd like the field to show on top of the main text area as shown. The case study ref field has been populated with content already, so it should show up if you're working on inserting it into the page template and styling it. Example page: https://inddex.nutrition.tufts.edu/data4diets/case-studies/brazil-health-and-environmental-impacts-excessive-meat-consumption-wfr!

![citationexample (1).jpg](https://images.zenhubusercontent.com/5e3b5a7454691a13cfdab601/aafd9f41-2b17-44c9-a0e7-8e897a718744)
![casestudyfield-userinterface.png](https://images.zenhubusercontent.com/5e3b5a7454691a13cfdab601/9e9a2b64-9103-4ec7-960d-76473ee3bdf2)
![casestudyfield-managefields.png](https://images.zenhubusercontent.com/5e3b5a7454691a13cfdab601/829db6cc-7fbe-4716-9760-55bebb481370)

**Tasks**

- [ ] review this issue and document in this ticket the approach you would take and the estimate

- [ ] Emily to send approach and estimate to client for approval

- [ ] Once approved, complete work

**Comment by eag603** [comment]
Xia is meeting with some of the stakeholders of this site. Xia will ask them how they are inputting the content.

**Comment by eag603** [comment]
Issue 2: 
1) ensure the field can handle the special characters - Eric
2) Also insert the field into the individual case study pages. 
3) Duplicate the formatting for that field that is in the work around screenshot. (h4)

**Comment by eag603** [comment]
Emily to split into two tickets.

**Comment by eag603** [comment]
This is done locally. Next step: testing and deploy to dev.

**Comment by ericmaster** [comment]
Deployed to dev and stage:

Dev: https://inddex-dev.nutrition.tufts.edu/data4diets/case-studies/brazil-health-and-environmental-impacts-excessive-meat-consumption-wfr
Stage: https://inddex-stage.nutrition.tufts.edu/data4diets/case-studies/brazil-health-and-environmental-impacts-excessive-meat-consumption-wfr

**Note:**

Considered cleaning up content added in body field, previously added as a workaround but would probably take more time (~3 to 4 hours) to implement and test so might be just easier to update the content manually once this is deployed to prod so the content does not display repeated.

**Comment by eag603** [comment]
with client for review
