### ISSUE TITLE
Update Drupal contrib modules

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#2]
**Site**
https://d1-connect-d8-develop.enroll.tufts.edu/

**Tasks**

- [ ] Update Drupal contrib modules
- [ ] Comment in ticket which contrib modules were updated
- [ ] Test
- [ ] Client review & fixes (if needed) - will happen first or second week of August
- [ ] Deploy to prod

**Comment by ericmaster** [comment]
**Notes:**

Did a quick review of release notes, did not notice any potentially breaking change

Updated contrib modules:

admin_toolbar (2.2.0 => 2.3.0)
bootstrap (3.21.0 => 3.23.0)
facets (1.4.0 => 1.5.0)
paragraphs (1.11.0 => 1.12.0)
taxonomy_multidelete_terms (1.1.0 => 1.3.0):
views_field_view (1.0.0-beta2 => 1.0.0-beta3)

Modules on dev that were updated to latest snapshot

authorization dev-1.x (7bc70e8 => 7e02d1e)
entity_reference_revisions dev-1.x (eec92af => 33c2b20)

**Comment by ericmaster** [comment]
Currently deployed to dev. There is some issue deploying to stage environment, once that is resolved will assign this ticket for review

**Comment by ericmaster** [comment]
Additional modules updates came up since last time this was reviewed.

- Reviewed release notes
- Resolved package dependency conflicts

Modules updated:

core_views_facets (1.1.0 => 1.2.0)
facets (1.5.0 => dev ca3970c) updated to latest dev to resolve dependency conflict with core_views_facets
time_range (1.2 => 9.0)

**Comment by ericmaster** [comment]
Verify no pending updates at https://d1-connect-d8-stage.enroll.tufts.edu/admin/modules/update
