### ISSUE TITLE
Update composer template

### ISSUE THREAD

**Issue by eag603** [isovera/Tufts-Friedman#4]
**Site**
https://d1-connect-d8-develop.enroll.tufts.edu/

**Tasks**

- [ ] As of the release of Drupal 8.8.0, the recommended composer template changed from drupal-composer/drupal-project to the officially supported drupal/recommended-project. Update the composer.json file to include the necessary components.
- [ ]   Comment in ticket how to test
- [ ] Test
- [ ] Client review & fixes (if needed) - will happen first or second week of August
- [ ] Deploy to prod

**Comment by ericmaster** [comment]
Updated the composer template accordingly to use the druapl/core-recommended and related packages from the drupal/recommended-project template.

Also removed some unnecessary outdated dependency (webflo/drupal-finder) primarily used by command line tools (drush and console)

Updated drush and console versions

**Comment by ericmaster** [comment]
Currently deployed to dev. There is an issue on the stage environment, once resolved will assign for review.

**Comment by ericmaster** [comment]
Deployed to stage, can be verified in repository https://gitlab.it.tufts.edu/esaidrp/d1-connect-d8-enroll-tufts-edu/-/blob/d1-connect-d8-stage/composer.json based on drupal recommeneded template https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-drupalrecommended-project
